### ISSUE TITLE
improve gpg/gpg-agent/pinentry error handling (e.g. ERROR session_hijacked)

### ISSUE THREAD

**Issue by olabini** [twstrike/Enigmail#12]

**Comment by iapazmino** [comment]
We need more details from the guys in Enigmail about what is it
they're envisioning. Fan and I have started a topic at the dev forum to try and get this information.

https://sourceforge.net/p/enigmail/forum/development/thread/7d062e8f/

The idea of starting the discussion on the forum instead of writing to them directly is so that the discussion is open to anyone else who wishes to collaborate with Enigmail have all the context they need.

**Comment by tcz001** [comment]
By Patrick Brunschwig 

16 hours ago
The main point here is that GnuPG issues various error messages that are currently not interpreted by Enigmail in other terms than "there is an error". If GnuPG issues such error messages, Enigmail should parse them an (depending on the situation) do something meaningful with it, e.g.:
display a warning dialog
ignore the error
abort processing
...
This is an extension to EnigmailCommon.parseErrorOutput (see check_hijacking).
